remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
color_scheme: "dark"
search_enabled: true
aux_links:
  "Download Package":
    - "https://github.com/brandonbiggs/marvin-robot/blob/master/marvin-wrapper.zip"
  "Idaho State University Computer Science":
    - "cs.isu.edu"