remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
color_scheme: "dark"
search_enabled: true
aux_links:
  "Idaho State University CS":
    - "https://www.isu.edu/cs/"
  "Download Package":
    - "https://github.com/brandonbiggs/marvin-robot/raw/master/marvin-wrapper.zip"